[build]
builder = "nixpacks"

[build.nixpacks]
buildCmd = "npx prisma generate && npm run build"

[deploy]
startCommand = "npx prisma migrate deploy && node dist/main"
healthcheckPath = "/"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
